### ISSUE TITLE
NE boundaries get "doubled" (visible while zooming in)

### ISSUE THREAD

**Issue by bdon** [protomaps/basemaps#119]

**Comment by bdon** [comment]
@nvkelso this boils down to duplication of NE boundaries from zooms 0-3 somehow

https://github.com/protomaps/basemaps/blob/main/tiles/src/main/java/com/protomaps/basemap/layers/Boundaries.java#L33

Can we remove the 50m dataset in favor of using the 10m dataset only?

**Comment by nvkelso** [comment]
I have an idea, let me submit a PR...
