### ISSUE TITLE
Help with getting more detailed map

### ISSUE THREAD

**Issue by Bragegs** [protomaps/basemaps#146]
First of all, **thank you so much** for all your hard work to make it possible to self-host maps. I've followed your guide to set up CDN + Lambda hosting and it works well.

I used https://protomaps.com/docs/downloads/basemaps to download planet basemap `protomaps-basemap-opensource-20230408.pmtiles`.

I find that in some of the examples from Protomaps, the map is more detailed than what I get from my map.

So my questions are:
1. Have I misconfigured something?
2. Do I need to build my own Planet basemap to get similar levels of detail? (Would it be possible to show how to build such a thing?)

example:
```
https://protomaps.github.io/PMTiles/?url=https%3A%2F%2Fr2-public.protomaps.com%2Fprotomaps-sample-datasets%2Fcb_2018_us_zcta510_500k.pmtiles#map=5.38/58.546/11.145
```

I know the zoom level is not perfectly matched in these two images -> but in higher zoom levels the difference in details are bigger.

My map (using 'protomaps-themes-base' base_theme('basemap', 'black'), and cdn+lambda vector tiles):
![Screenshot 2023-10-02 at 08 08 57](https://github.com/protomaps/basemaps/assets/10655264/4c581841-22fa-48d9-8645-d73c986c932f)
Protomaps example:
![Screenshot 2023-10-02 at 08 09 00](https://github.com/protomaps/basemaps/assets/10655264/6a93d500-6e82-4a27-ba75-842ee7073d17)

**Comment by Bragegs** [comment]
Mapped through layers array from protomaps-themes-base and changed the properties to style it how I wanted.

**Comment by bdon** [comment]
Hi, 

If you're using styles v2+ you'll need a v3 tileset. The link you posed above is for a v2 tileset.

The daily builds of v3 tilesets are listed here: https://maps.protomaps.com/builds/

will update the docs in the next week to point to this. work in progress!

**Comment by Bragegs** [comment]
Thank you @bdon, that helps a lot 👍
