### ISSUE TITLE
Turn labels to any locale

### ISSUE THREAD

**Issue by emilienbidet** [protomaps/basemaps#149]
**Description**
I would like to have labels written in french : country and city names

A great solution would be to be able to do it by giving an option to the function like this : 

```ts
layers("protomaps", "light", {
  locale: "fr"
})
```

**Comment by bdon** [comment]
Thanks, this will come in one of the next majors version of the tileset/styles: see #112

For now exporting a style JSON and replacing `name` with `name:fr` should somewhat work.

**Comment by emilienbidet** [comment]
So cool ! Thank you very much @bdon !

**Comment by emilienbidet** [comment]
I now close this issue to no create a duplicate
