### ISSUE TITLE
Circles without correspnding label appearing

### ISSUE THREAD

**Issue by daniel-j-h** [protomaps/basemaps#167]
When zooming into the map on some zoom layers it looks like circle appear without corresponding labels.

Have a look at the screenshots below; in the second one I'm highlighting the issue in red (zoom in).

I believe this is the case because we have
- a circle layer
- a symbol layer for the text, with an anchor on the left (or center, conditionally)

I think this is how we could fix it
1. We don't do anything and don't care that circles without labels are appearing
2. Instead of a circle layer and a symbol layer for text only, we could have a single symbol layer and use text+icon in a single layer
3. We add variable anchors so that the labels still show up when the left/center anchor doesn't work out

https://maplibre.org/maplibre-style-spec/layers/#layout-symbol-text-variable-anchor

Note: the screenshots are from the latest map on https://maps.protomaps.com

![basemap0](https://github.com/protomaps/basemaps/assets/527241/e402f03e-ee66-4b01-a501-1b50d730a713)
![basemap1](https://github.com/protomaps/basemaps/assets/527241/725b17e8-0be9-46e9-b519-c561fcd800e2)
![basemap2](https://github.com/protomaps/basemaps/assets/527241/2fd4c98c-c69e-41a4-be51-d49099158111)

**Comment by nvkelso** [comment]
Great feedback, thank you! I agree the text and icon symbols should be consolidated into single draw style layer. 

We’re working on that now with the active icon sprint and new basemap styles @bdon can talk more about, in collaboration with @sensescape.

**Comment by bdon** [comment]
This is related to #160 because to make text + circle into a unified layer we need to use the Symbol layer type. 

I just created https://github.com/protomaps/basemaps-assets with placeholder assets - I think using GitHub pages with no build step is the most obvious and transparent place to put sprites/fonts for the basemap. will begin to flesh this out and gather some feedback before we commit to using those URLs

**Comment by bdon** [comment]
This is resolved with the addition of spritesheets in styles v3.0.0

<img width="576" alt="Screenshot 2024-05-10 at 16 18 30" src="https://github.com/protomaps/basemaps/assets/77501/e7933a35-d8bb-43a6-9eec-e6e412395a58">
