### ISSUE TITLE
Add to Taginfo Projects

### ISSUE THREAD

**Issue by danieldegroot2** [protomaps/basemaps#170]
Show the OpenStreetMap community what [data](https://wiki.openstreetmap.org/wiki/Tags) you are using. Add your project to the [list](https://taginfo.openstreetmap.org/projects) of [Taginfo Projects](https://github.com/taginfo/taginfo-projects).

**Comment by danieldegroot2** [comment]
Hey @bdon,

Could you let me know your reason for closing this issue, please?
It is understandable if it is not planned or similar.

**Comment by bdon** [comment]
While it would be nice to see all the used tags in taginfo, there isn't a straightforward way to compile all tag uses in the source code right now, so this isn't planned.
