### ISSUE TITLE
Style Data for the Base Maps? Raster?

### ISSUE THREAD

**Issue by coogle** [protomaps/basemaps#187]
I apologize if this isn't the proper place to ask this, but as a relative newbie to this project I couldn't figure out the answer I was looking for here. 

I am trying to integrate protomaps via AWS Lambda function into a Flutter application (following https://docs.protomaps.com/deploy/aws). I think I've done a decent job of getting the server itself working as I can make requests and get `.mvt` files back from my lambda function, but I am not sure what I need to actually tie this into my map widget. It seems to require some sort of style JSON -- here's the relevant part of an example taken provided for one of the commercial vendors:

```dart
  Future<Style> _readStyle() => StyleReader(
          uri:
              'https://tiles.stadiamaps.com/styles/osm_bright.json?api_key={key}',
          apiKey: stadiaMapsApiKey,
          logger: const Logger.console())
      .read();
      
```

It seems to me I need this style JSON file for these base maps, if I am understanding it correctly? I see some code in the various repos for styles, but how to use it, etc. is unclear. Are there styles available somewhere I'm missing? The docs reference them but they are all blank pages (mostly, at least). 

Secondary question: If I understand correctly pmtiles can also be used for raster tiles, correct? Is there any documentation for creating a raster tileset (in case I can't get the vector tiles working with my system in the short term)? When I try to make a request for `.png` files (for example) I get back an error saying only `.mvt` is available.

**Comment by prusswan** [comment]
It would be convenient if the `style.json` for the respective default styles is also provided as part of the API (would make it easier to use with https://maputnik.github.io). One workaround to get a hosted style json, is to use the daily builds https://maps.protomaps.com/builds/ -> Compare in Maperture -> something like https://build-metadata.protomaps.dev/style@2.0.0-alpha.0+theme@light+tiles@20230925.json

**Comment by bdon** [comment]
@prusswan in many cases it's easier to "assemble" a style JavaScript object (not JSON) by grabbing the layers from e.g. https://unpkg.com/protomaps-themes-base@2.0.0-alpha.0/dist/layers/light.json and providing your own `sources` key. 

That doesn't address the case of Maputnik, etc though. What I may do is just spin up an editor interface with the right style.json preloaded? Is there another case for needing a style.json? 

I have that as part of the hosted API with API keys?

`https://api.protomaps.com/styles/v2/dark.json?key=KEY`

**Comment by prusswan** [comment]
> I have that as part of the hosted API with API keys too:

That's neat and exactly what @coogle and I was looking for. Would be great to mention in the docs (e.g. https://protomaps.com/other), especially for users familiar with Mapbox/OpenMapTiles etc. Did not know about `protomaps-themes-base` as I only found this repo and thought users were expected to build the style.json themselves

>  Is there another case for needing a style.json?

Other than the online maputnik, I use it for working with other map clients and libraries where it is convenient to download/reference a style that already exists and just override the tile url or strip out the parts I don't need

**Comment by bdon** [comment]
I listed out the hosted style endpoints at https://protomaps.com/other

The styles as part of the open source project have source code at https://github.com/protomaps/basemaps/tree/main/styles and also are compiled into layers objects like this: http://unpkg.com/protomaps-themes-base@2.0.0-alpha.5/dist/layers/dark.json - seems easiest to let you assemble your own `Style` object with the correct `sources` keys. Let me know if you find a better way!

**Comment by prusswan** [comment]
Due to site changes, relevant info is now at: https://docs.protomaps.com/basemaps/maplibre#loading-styles-as-json

Example below for static html:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MapLibre - Protomaps</title>
    <script src="https://cdn.jsdelivr.net/npm/maplibre-gl@latest/dist/maplibre-gl.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/maplibre-gl@latest/dist/maplibre-gl.css" rel="stylesheet"/>

    <script src="https://unpkg.com/pmtiles@3.2.0/dist/pmtiles.js"></script>
    <script src="https://unpkg.com/@protomaps/basemaps@5/dist/basemaps.js" crossorigin="anonymous"></script>

    <style>
        body, html {
            margin: 0;
            padding: 0;
            height: 100%;
        }
        #map {
            height: 100%;
            width: 100%;
        }
    </style>
</head>
<body>
    <div id="map"></div>
    <script>
      // adapted from https://maplibre.org/maplibre-gl-js/docs/examples/pmtiles/

      // add the PMTiles plugin to the maplibregl global.
      const protocol = new pmtiles.Protocol();
      maplibregl.addProtocol('pmtiles', protocol.tile);

      const PMTILES_URL = "https://data.source.coop/protomaps/openstreetmap/v4.pmtiles";
      const p = new pmtiles.PMTiles(PMTILES_URL);

      // this is so we share one instance across the JS code and the map renderer
      protocol.add(p);

      // we first fetch the header so we can get the center lon, lat of the map.
      p.getHeader().then(h => {
        const map = new maplibregl.Map({
            container: 'map', // container id
            style: {
                version: 8,
                glyphs:'https://protomaps.github.io/basemaps-assets/fonts/{fontstack}/{range}.pbf',
                sprite: "https://protomaps.github.io/basemaps-assets/sprites/v4/light",
                sources: {
                    "protomaps": {
                        type: "vector",
                        url: `pmtiles://${PMTILES_URL}`,
                        //       ^-- Remember to prefix the URL with pmtiles://
                        attribution: '<a href="https://protomaps.com">Protomaps</a> © <a href="https://openstreetmap.org">OpenStreetMap</a>'
                    }
                },
                layers: basemaps.layers("protomaps",basemaps.namedFlavor("light"),{lang:"en"})
            },
            center: [0, 0], // starting position [lng, lat]
            zoom: 1 // starting zoom
        });
      });
    </script>
</body>
</html>
```
