### ISSUE TITLE
export 'default' (imported as 'layers') was not found in 'protomaps-themes-base' (module has no exports)

### ISSUE THREAD

**Issue by devinmarkley** [protomaps/basemaps#236]
**Required information**
 - Browser: Chrome
 - Renderer version MapLibre GL JS 1.22.19
 - Tileset version: 20230918.pmtiles
 - source: [https://maps.protomaps.com/builds/](https://maps.protomaps.com/builds/)
 protomaps-themes-base: 1.22.19
 
 Code:
 `import { useEffect } from "react";
import Map from "react-map-gl";
import maplibregl from "maplibre-gl";
import "maplibre-gl/dist/maplibre-gl.css";
import { Protocol } from "pmtiles";
import layers from "protomaps-themes-base";

export default function MaplibreViewer() {
  useEffect(() => {
    let protocol = new Protocol();
    maplibregl.addProtocol("pmtiles", protocol.tile);
    return () => {
      maplibregl.removeProtocol("pmtiles");
    };
  }, []);

  return (
    <div>
      <Map
        style={{ width: 600, height: 400 }}
        mapStyle={{
          version: 8,
          sources: {
            protomaps: {
              type: "vector",
              url: "pmtiles://https://mycloud_basemapw.pmtiles",
              attribution:
                '<a href="https://protomaps.com">Protomaps</a> © <a href="https://openstreetmap.org">OpenStreetMap</a>',
            },
          },
          layers: layers("protomaps", "light"),
        }}
        mapLib={maplibregl}
      />
    </div>
  );
}`

Problem:

export 'default' (imported as 'layers') was not found in 'protomaps-themes-base' (module has no exports)

Any help would be greatly appreciated.

Thanks

**Comment by bdon** [comment]
> protomaps-themes-base: 1.22.19

please use version 2.0.0-alpha.6

**Comment by devinmarkley** [comment]
Just updated to the most recent version and I'm getting the same issue.

export 'layers' (imported as 'layers') was not found in 'protomaps-themes-base' (module has no exports)

Code:

import { useEffect } from "react";
import Map from "react-map-gl";
import maplibregl from "maplibre-gl";
import "maplibre-gl/dist/maplibre-gl.css";
import { Protocol } from "pmtiles";
import { layers } from 'protomaps-themes-base';

export default function MaplibreViewer() {
  useEffect(() => {
    let protocol = new Protocol();
    maplibregl.addProtocol("pmtiles", protocol.tile);
    return () => {
      maplibregl.removeProtocol("pmtiles");
    };
  }, []);

  return (
    <div>
      <h1>Hello World</h1>
      <Map
        style={{ width: 600, height: 400 }}
        mapStyle={{
          version: 8,
          sources: {
            protomaps: {
                type: "vector",
                url: "pmtiles://https://example.com/example.pmtiles",
                //       ^-- Remember to prefix the URL with pmtiles://
                attribution: '<a href="https://protomaps.com">Protomaps</a> © <a href="https://openstreetmap.org">OpenStreetMap</a>'
            }
          },
            layers: layers("protomaps","light")
        }}
        mapLib={maplibregl}
      />
    </div>
  );
}

**Comment by bdon** [comment]
Can you please try protomaps-themes-base@2.0.0 and push a minimal repo to reproduce the above steps including package.json and build tool / step?

**Comment by devinmarkley** [comment]
Thanks for working with me on this I really appreciate it.
 
Moving from 2.0.0-alpha.6 to simply ^2.0.0 seems to some my issues with the module having no exports. However while I no longer get this error with this change the map still doesn't get styled correctly. I have linked a minimal repo with the package.json below.

[link](https://github.com/devinmarkley/protomaps-export-default-imported-as-layers-was-not-found-)

**Comment by bdon** [comment]
you are missing the `glyphs` key in your style as the console error shows, see https://docs.protomaps.com/basemaps/maplibre

<img width="636" alt="Screenshot 2024-04-20 at 10 01 40" src="https://github.com/protomaps/basemaps/assets/77501/2b52239d-7955-4d96-bba0-328d0b077aaa">
