### ISSUE TITLE
City name "Poitiers" not completely displayed when using MapLibre

### ISSUE THREAD

**Issue by pietervdvn** [protomaps/basemaps#247]
**Location**

Laloutre created the following issue, which is copied here: https://github.com/pietervdvn/MapComplete/issues/1946 . The issue only appears if `z<7`

I was on the page https://mapcomplete.org/cafes_and_pubs.html?z=8.7&lat=46.50507186825013&lon=0.41305714811585403 and i noticed that the city name wasn't the same depending on the zoom level. "Poitier" without an "s" before zooming, then the correct name when zooming ( attached screenshots) .  I'm not sure if this bug is linked to your project. 

![Screenshot_2024-05-10-09-43-22-950_org mozilla firefox](https://github.com/pietervdvn/MapComplete/assets/2885740/2a86805d-8639-4fdc-ac3f-fedb0081be23)
![Screenshot_2024-05-10-09-43-31-528_org mozilla firefox](https://github.com/pietervdvn/MapComplete/assets/2885740/ebcbdc06-7be4-45f4-a20f-0bd13988828f)

Reproducible on the protomaps homepage: 
![image](https://github.com/pietervdvn/MapComplete/assets/1466478/169fc058-135d-4926-b3ba-3ec31665c132)
https://protomaps.com/

**Required information**
 - Browser: Librewolf (Firefox)
 - Renderer version: MapLibre 4.1.1
 - Tileset version and source: 13 may, https://api.protomaps.com/tiles/v3.json
 - Style JSON: Protomaps Light, Protomaps Sunny (MapComplete specific rendering)

**Comment by bdon** [comment]
Thanks for the detailed issue report!

The names in these situations are coming from different sources (NE/OSM), we should clean the logic here up along with #112

**Comment by bdon** [comment]
This should be fixed in tomorrow's build (4.0.0-alpha.3)

**Comment by bdon** [comment]
![CleanShot 2024-08-24 at 20 09 01@2x](https://github.com/user-attachments/assets/555ee2db-ba9a-4505-8a63-3c1dcdda5802)

https://maps.protomaps.com/#map=6.75/46.177/0.022&theme=light&tiles=https://build.protomaps.com/20240824.pmtiles

The name mismatches should be resolved in the daily tile build, the hosted API should be updated in a few weeks with v4.
