### ISSUE TITLE
Buildings with 'railway'-tag also show a railway outline

### ISSUE THREAD

**Issue by pietervdvn** [protomaps/basemaps#249]
**Location**

[This building](https://www.openstreetmap.org/way/267216510#map=19/51.98456/5.90419&layers=N) has `building=commercial` and `railway=signal_box`. It is included in both railway- and buildings-layer and renders as such:

![image](https://github.com/protomaps/basemaps/assets/1466478/a24b0c0c-d317-41b9-9553-d29140be078e)
This is more pronounced in my Sunny-rendering:
![image](https://github.com/protomaps/basemaps/assets/1466478/6217b93b-9149-47fd-acb7-7f5f0f41f77c)

Original report: https://github.com/pietervdvn/MapComplete/issues/1953

**Required information**
Browser(s): Chrome 124.0.6367.202, 124.0.6367.208, librewolf (Firefox)
OS: Windows 10, Ubuntu
 - Renderer version: MapLibre GL JS 4.1.1
 - Tileset version and source: protomaps hosted

**Comment by nvkelso** [comment]
I suspect this feature appearing in both the Buildings layer correctly and the Transit layer incorrectly is caused by allowing fallback passthru `railway=*` values in the Transit layer instead of using an explicate allowlist (or adding a blocklist):

- https://github.com/protomaps/basemaps/blob/main/tiles/src/main/java/com/protomaps/basemap/layers/Transit.java#L55-L66

Do you want to submit a PR with a fix?

**Comment by bdon** [comment]
Note for later: it's possible for `building=yes` and `railway=platform` : https://www.openstreetmap.org/way/166152585 

tilezen visualizes platforms as polygons in the transit layer https://tilezen.readthedocs.io/en/latest/layers/#transit

**Comment by pietervdvn** [comment]
Thanks for adding a testcase! I was AFK for a few days.

**Comment by bdon** [comment]
@pietervdvn thanks for the PR, 3.5.2 will run as today's daily build http://maps.protomaps.com/builds/ and then I'll update the API afterwards.

**Comment by bdon** [comment]
The hosted API has been updated, but it may take a bit for cached tiles to fall out.

**Comment by wipfli** [comment]
Adding a render test for this in #485
