### ISSUE TITLE
Static Images like Mapbox

### ISSUE THREAD

**Issue by SkyTik** [protomaps/basemaps#271]
**Description**
I'm looking for a way to create static images like Mapbox, does Protomaps support this feature?

**Mapbox Sample**
[Mapbox Static Images Playground](https://docs.mapbox.com/playground/static/)

**Comment by bdon** [comment]
That is a feature of MapLibre native, so please refer to the documentation for that project. You can use the protomaps tilesets/JSON styles with MapLibre native.
