### ISSUE TITLE
Fountain gets lake label

### ISSUE THREAD

**Issue by wipfli** [protomaps/basemaps#279]
The "Rebekkabrunnen" (Rebecca Fountain) in Zürich gets what looks like a lake label.

https://maps.protomaps.com/#map=19.06/47.3669738/8.53999&theme=light&tiles=https://build.protomaps.com/20240730.pmtiles

![Screenshot_20240730-193721](https://github.com/user-attachments/assets/b5eb171d-0184-421b-8394-52b5fa851e4d)

I think that should be a POI instead...

**Comment by wipfli** [comment]
https://www.openstreetmap.org/way/667718519

It has natural=water and amenity=fountain

**Comment by wipfli** [comment]
Thanks for the proposed fix @bdon. Unfortunately, it looks like the lake label on this fountain is still present: 

![image](https://github.com/user-attachments/assets/b2a2e612-6f4b-4aec-9046-555fcef02b69)

https://maps.protomaps.com/#map=19.61/47.3670034/8.54007&theme=light&tiles=https://build.protomaps.com/20240808.pmtiles

**Comment by bdon** [comment]
Fixed in latest: https://maps.protomaps.com/#map=19.71/47.3670042/8.5400825&theme=light&lang=en&tiles=https://build.protomaps.com/20241003.pmtiles
