### ISSUE TITLE
Tiles and styles 4.0.0

### ISSUE THREAD

**Issue by bdon** [protomaps/basemaps#282]
**DESCRIPTION**

**Breaking changes:**

* drop `pmap:` prefixes from tag names to align with tilezen.
* Remove deprecated OSM tags in favor of `kind`
* remove `physical_point`, `natural` and `physical_line` layers to align with tilezen. features go into the `landuse` or `water`, `poi` or `earth` layers.

**Resolve other issues:**

* #256
* #112 

@nvkelso @wipfli

**Comment by wipfli** [comment]
For v4 I would like to segment names by script #273 and remove the `pgf:` prefix (store pgf encoded strings by default, have bare unicode in other property).

**Comment by bdon** [comment]
@nvkelso we also need to collapse `roads` > `medium_road` into `major_road` (with appropriate `kind_detail`)

**Comment by nvkelso** [comment]
While Tilezen 1.x series doesn't have a separate layer for OSM `natural` tagged features, in v2 we said those should go into a `landcover` layer in https://github.com/tilezen/vector-datasource/issues/2025 and related https://github.com/protomaps/basemaps/issues/154.

**Comment by nvkelso** [comment]
> remove physical_point, natural and physical_line layers to align with tilezen. features go into the landuse or water, poi or earth layers.

Are you ok with mixed geometry types in the MVT layers like Tilezen had?

**Comment by nvkelso** [comment]
> Remove deprecated OSM tags in favor of kind

Need to ensure `kind_detail` captures the appropriate raw OSM values. I _think_ it does today, but it's the combo of `kind` and `kind_detail` that makes dropping the raw tags possible.

**Comment by bdon** [comment]
> Are you ok with mixed geometry types in the MVT layers like Tilezen had?

We need to add geometry type filters to the style.

> While Tilezen 1.x series doesn't have a separate layer for OSM natural tagged features, in v2 we said those should go into a landcover layer in https://github.com/tilezen/vector-datasource/issues/2025 and related https://github.com/protomaps/basemaps/issues/154.

I am already separating out daylight landcover into a new `landcover` that is not part of Tilezen. 

Plan is to keep OSM landcover in `landuse` for Tangram preservation reasons until 5.0.

**Comment by bdon** [comment]
breaking changes to tiles merged in https://github.com/protomaps/basemaps/commit/55d0df23a0091f810eafbbd5b156b8783f181ef4

will follow up with style changes

**Comment by bdon** [comment]
Both tiles and styles have been merged now.
