### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by sing78** [protomaps/basemaps#30]
When trying to execute this command:" mvn clean package "

I get this error:
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project protomaps-basemap: Fatal error compiling: error: invalid target release: 16

I solved this after upgrading to Java 17.

Now works as expected.

**Comment by bdon** [comment]
Updated Readme to indicate Java 17+. thanks.
