### ISSUE TITLE
final touches on 4.0 breaking changes

### ISSUE THREAD

**Issue by bdon** [protomaps/basemaps#303]
@nvkelso

* fold `kind=medium_road` into `kind=major_road`: [Tilezen roads](https://github.com/tilezen/vector-datasource/blob/master/docs/layers.md#road-properties-common)
* remove non-integer `kind_detail` from `boundaries`. remove `min_admin_level` and fold into `kind_detail`. [tilezen boundaries](https://github.com/tilezen/vector-datasource/blob/master/docs/layers.md#boundaries-properties-common)
* rename `ele` to `elevation` in POIs [tilezen pois](https://github.com/tilezen/vector-datasource/blob/master/docs/layers.md#poi-properties-only-on-kindpeak-and-kindvolcano)
* remove integer `level` from `roads` and replace with `is_bridge=true` or `is_tunnel=true` [tilezen roads](https://github.com/tilezen/vector-datasource/blob/master/docs/layers.md#poi-properties-only-on-kindpeak-and-kindvolcano)

Note: Tangram relies on `sort_rank` for proper layering which is not possible with MapLibre GL, so maybe we want to keep integer `level`?

Still working through one more issue with `kind=rail` appearing in `roads` layer.

**Comment by nvkelso** [comment]
> Note: Tangram relies on sort_rank for proper layering which is not possible with MapLibre GL, so maybe we want to keep integer level?

Yes, ok to keep `level` to allow semi-complicated over/under road layering. Though for perf and simplicity these are often flattened to just 3 sets of layers (any tunnels of a given kind, any surface of a given kind, any bridges of a given kind).

**Comment by bdon** [comment]
I think we need to migrate all current `rail=` (physical rail) into `roads` (transportation), which shows up quite late (~z13), and then leave `transit` empty. `transit` in a later 4.x release will be abstract services (Subway, HSR, etc) that appears at lower zoom levels.

@nvkelso let me know if this is consistent with your design, as well as `kind_detail` in boundaries above?

**Comment by nvkelso** [comment]
Yes, sounds good

**Comment by bdon** [comment]
Closing this one out. Will address `level` likely via the server-assisted approach in #72
