### ISSUE TITLE
Ferry line labels

### ISSUE THREAD

**Issue by wipfli** [protomaps/basemaps#312]
**Location**
Geneva high zoom

https://maps.protomaps.com/#map=15.92/46.206564/6.149963&theme=light&lang=en&tiles=https://build.protomaps.com/20241004.pmtiles

**Screenshots**
![Screenshot_20241004-194357](https://github.com/user-attachments/assets/1a261832-ad0e-42d3-b346-dad5464789b1)

Are labels on ferry lines on purpose?

**Comment by nvkelso** [comment]
Doh! Ferry line labels should be excluded from early- and mid-zooms as they confuse most people (they are often long strings of text, and make it look like there is a road in the water when it's a ferry instead). 

Ferry line labels are optional to taste somewhere between zooms 16 and 18. I'd recommend 18 for Protomaps. What to file a PR? They should also use a different text treatment than road labels, perhaps blue italic text?

**Comment by bdon** [comment]
ferry lines seem to be getting `kind=other` and thus labeled because it's looking for `ferry=*` in OSM: https://github.com/protomaps/basemaps/blob/main/tiles/src/main/java/com/protomaps/basemap/layers/Roads.java#L228

This seems like a mistake relative to Tilezen v1.9, will open a PR

**Comment by bdon** [comment]
Fixed in 4.0.1
