### ISSUE TITLE
no Min Height in buildings layer

### ISSUE THREAD

**Issue by JfrAziz** [protomaps/basemaps#323]
I want to show 3D building from `buildings` layer, and for some buildings we need `min_height`. here the result:

![image](https://github.com/user-attachments/assets/7d4ca66c-0e21-4b28-9a58-45fd763f7bbd)

for comparison from [openfreemap](https://openfreemap.org/):

![image](https://github.com/user-attachments/assets/b84769b4-5d46-4665-9d7b-afcfc3e6511a)

```json
{
      "id": "buildings-3d",
      "type": "fill-extrusion",
      "source": "protomaps",
      "source-layer": "buildings",
      "minzoom": 14,
      "paint": {
        "fill-extrusion-base": [
          "get",
          "min_height"
        ],
        "fill-extrusion-color": "hsl(35,8%,85%)",
        "fill-extrusion-height": [
          "get",
          "height"
        ],
        "fill-extrusion-opacity": 1
      }
    },
```

I am not familiar with layers generation, but is this line correct?

https://github.com/protomaps/basemaps/blob/f7bcb4869434030ba23271f43e9dbcf6bfc5d63f/tiles/src/main/java/com/protomaps/basemap/layers/Buildings.java#L20

**Comment by nvkelso** [comment]
This looks like a bug (should be min_height), can you submit a PR?

**Comment by bdon** [comment]
> minimum default building height when the height is null

Right, we should probably add a toggle for 3D/non-3D buildings in our default style... or default to one or the other?

**Comment by JfrAziz** [comment]
just for update, looks like new version still no min_height. here when I inspect with maputnik

![image](https://github.com/user-attachments/assets/f65ac393-74f7-4789-9eaf-2b8221c5ee8a)

**Comment by bdon** [comment]
are you using the hosted api.protomaps.com or your own file?

**Comment by JfrAziz** [comment]
my own file, from build, just check another location, some location has `min_height`. 
![image](https://github.com/user-attachments/assets/cae85af5-e9ea-4c6b-bb80-b480fc4f1388)

**Comment by bdon** [comment]
here is the latest file with date November 6 that has min_height for London eye

https://pmtiles.io/?url=https%3A%2F%2Fdemo-bucket.protomaps.com%2Fv4.pmtiles#map=17.9/51.502967/-0.119692

can you tell me what is the version for the file you are looking at? visible with `pmtiles show`

**Comment by JfrAziz** [comment]
sorry, caching issues. I see outdated version after update. 

![image](https://github.com/user-attachments/assets/6a791fa6-a928-4046-9bfc-468552323c66)

thanks for help, here the styles I am using

```json
{
  "id": "buildings-3d",
  "type": "fill-extrusion",
  "source": "protomaps",
  "source-layer": "buildings",
  "minzoom": 14,
  "paint": {
    "fill-extrusion-base": [
      "coalesce",
      ["get", "min_height"],
      0
    ],
    "fill-extrusion-color": "hsl(35,8%,85%)",
    "fill-extrusion-height": [
      "coalesce",
      ["get", "height"],
      10
    ],
    "fill-extrusion-opacity": 1
  },
  "filter": [
    "any",
    ["!", ["has", "kind_detail"]],
    ["!=", ["get", "kind_detail"], "no"]
  ]
}
```

that `kind_detail` =  `no` that has min_height 1.5 and height 400 make London Eye boxed.

![image](https://github.com/user-attachments/assets/d2b730f5-312e-4552-b7f9-2033d0d0f809)

**Comment by do-me** [comment]
@JfrAziz or @bdon would you mind sharing a minimal protomaps + maplibre 3D example? I'm also interesting in displaying maps just like you showcased.

**Comment by JfrAziz** [comment]
here's mine https://github.com/datawan-labs/maps

**Comment by do-me** [comment]
Perfect, thanks a lot for sharing!
