### ISSUE TITLE
What is the correct way to create pmtiles?

### ISSUE THREAD

**Issue by sing78** [protomaps/basemaps#33]
Hi,
I am trying to create pmtiles from a osm.pbf file (from Geofabrik).
I tried two ways:

1) tippecanoe -o output.mbtiles -zg --drop-densest-as-needed --extend-zooms-if-still-dropping input.osm.pbf
   pmtiles convert input.mbtiles output.pmtiles

2) osmium export data.osm.pbf --format geojsonseq > data.geojson
   tippecanoe -zg -o data.mbtiles -f data.geojson
   pmtiles convert data.mbtiles data.pmtiles

Here is the html code.I am using a protomaps basemaps style (the 'light" one) for MapLibre GL JS.
[albania.txt](https://github.com/protomaps/PMTiles/files/11069127/albania.txt)
Using the same html code,when I use pmtiles downloaded from protomaps web site,everything works fine.

What am I missing?Is this something I should do when convertin from one file type to another?

Thanks

**Comment by HeikoGr** [comment]
I was able to create pmtiles in this way:

```
sudo apt install openjdk-17-jdk maven

git clone https://github.com/protomaps/basemaps/
cd basemaps/tiles

mvn clean package

java -jar target/*-with-deps.jar --download --area=monaco --maxzoom=10 --output=monaco-z10.pmtiles --force
```

But limited by my memory I was not able to create a world map directly.

i needed to create mbtiles first (with the protomaps profiles, for every 8 regions geofabrik.de offers), then combine it with tile-join from github.com/felt/tippecanoe and convert it with pmtiles from github.com/protomaps/go-pmtiles .

**Comment by wipfli** [comment]
How much memory do you have?

**Comment by HeikoGr** [comment]
32gb on the (proxmox) host. i assigned 24gb to the virtual machine and added the argument "-Xmx18g" to the java command mentioned above.

**Comment by HeikoGr** [comment]
> How much memory do you have?

Inspired by your question i dug deeper and was able to run planet osm in one run (with maxzoom=10) in 4h.

`java -Xmx18g -jar target/*-with-deps.jar --area=planet --maxzoom=10 --bounds=planet --download --download-threads=10 --download-chunk-size-mb=1000 --fetch-wikidata --output=output.pmtiles --nodemap-type=array --storage=mmap --force `

(Sidenote: needed to predownload the planet osm file with planetiler, so the command here is a bit misleading)

**Comment by bdon** [comment]
Yes, you need `--nodemap-type=array --storage=mmap` to avoid using lots of memory. Please re-open if you encounter other issues.
