### ISSUE TITLE
Height tag from levels

### ISSUE THREAD

**Issue by bdon** [protomaps/basemaps#34]
Right now we only consider the height if tagged with meters, we should do something reasonable with levels as well. 

example in Bellevue, WA: https://www.openstreetmap.org/way/91367308

**Comment by wipfli** [comment]
Also, overture is using the `est_height` tag which can be useful.

**Comment by bdon** [comment]
Using the logic for height from levels here: https://github.com/tilezen/vector-datasource/blob/master/vectordatasource/util.py#L55
