### ISSUE TITLE
Map of Germany

### ISSUE THREAD

**Issue by riccarcharias** [protomaps/basemaps#36]
Hi, I love pmtiles as it works fast and easy. I need a map of Germany and on photomaps.com you can only download a world map (which is way to big in file size) or smaller local maps.

Whats's the best way to get a map of a country like Germany. I just need the normal basemap with street names with out POIs. Thanks!

**Comment by bdon** [comment]
https://github.com/protomaps/basemaps#usage - replace the region with any region you want to generate it!

**Comment by riccarcharias** [comment]
Thanks for your answer @bdon , I tried to get this working for two hours but I have no idea how to work with commands in the console...I just never did that. I downloaded the basemaps-main and I just don't know how to work with these files using commands. I tried Visual Studio Code, Terminal on macOS, I couldn't connect to GitHub because the permission was denied and the README is really short...I'm very new to all this map-creating, sorry...I watched tutorials for 2 hours but they also didn't really helped me...

Maybe a few short questions that would help me getting started: 

**Do I need Planetiler to get this working?**

**How can I use commands to do tasks targeting the basemaps-main folder? What app / terminal would you recommend? Do you know a tutorial / guide how it's done?** 

Sorry for my stupidity but I just never hat to use the terminal commands in connection with 3rd-party scripts. But at least I know how to work with pmtiles and leaflet on a webpage ^^

**Comment by wipfli** [comment]
Have you tried asking your questions to ChatGPT? For me, the service has been very helpful to learn new technologies...

**Comment by bdon** [comment]
@riccarcharias  Here is the output of running that command:

https://r2-public.protomaps.com/tmp/germany.pmtiles

[visual preview](https://protomaps.github.io/PMTiles/?url=https%3A%2F%2Fr2-public.protomaps.com%2Ftmp%2Fgermany.pmtiles#map=5.33/51.376/10.458)

**Comment by riccarcharias** [comment]
@bdon you really rocked it, you are awesome, thank you very much!!! It works perfectly!

**Comment by riccarcharias** [comment]
@wipfli Thanks for your suggestion using ChatGPT. I tried it but the AI said, this is a python script. I told them that it's not correct but the answers didn't got any better. I still don't know how the workflow is creating my own .pmtiles map...
