### ISSUE TITLE
Consider adding sports, craft, and historic tags with raw coalesce option for kind/tag

### ISSUE THREAD

**Issue by nvkelso** [protomaps/basemaps#39]
In the closed PR, @tyrauber noted that the `sports`, `craft`, and `historic` tags could be exported in raw form as well, and added to the coalesce of values in the exported `pmaps:kind` property. 

There's another interesting idea here which is to always pass thru the raw values of the tags in a new `pmaps:tag` property – since the `pmaps:kind` property is an gated allowlist of properties (else "other" when not in the allowlist). Adding this would facilitate data-driven icon lookups based on single property instead of a list of properties.

From the original PR comment:

              Hi @nvkelso, it looks @bdon has already addressed my suggestions on main!

- stars are applied to point features as `stars`:
```
           point_feature.setAttr("stars", sf.getString("stars"));
```
- `pmap:tag` is not necessary because tag values can be accessed by key name: 
```
          .setAttr("amenity", sf.getString("amenity"))
          .setAttr("shop", sf.getString("shop"))
          .setAttr("railway", sf.getString("railway"))
          .setAttr("cuisine", sf.getString("cuisine"))
          .setAttr("religion", sf.getString("religion"))
          .setAttr("tourism", sf.getString("tourism"))
          .setAttr("iata", sf.getString("iata"))
```

It's missing the `sports` , `craft` and `historic` tag.  Sports and craft are probably unnecessary, but for tourism implementations, I'd probably add historic.

All in all the implementation on main is more flexible than the approach I came up with. :+1: Closing.

_Originally posted by @tyrauber in https://github.com/protomaps/basemaps/issues/32#issuecomment-1573846069_

**Comment by nvkelso** [comment]
I've addressed most of this in https://github.com/nvkelso/basemaps/commit/d452bbe1be9d0f2483c8eda36884a4894edfafb9, which is in WIP PR https://github.com/protomaps/basemaps/pull/47.

**Comment by nvkelso** [comment]
#47 has been merged, this issue can be closed as complete.

**Comment by bdon** [comment]
@nvkelso from what I can tell a single icon lookup is not possible purely on `pmap:kind`, we have to consider `kind_detail` for classes like `place_of_worship`. What's our strategy here? (Prefer moving any complexity to tiles instead of style)
