### ISSUE TITLE
POI for way with `shop=supermarket` is missing

### ISSUE THREAD

**Issue by wipfli** [protomaps/basemaps#48]
https://www.openstreetmap.org/way/87991871 is a way which is tagged as `shop=supermarket`. The protomaps basemap includes nodes with this tag in the POI layer, but ways seem to be missing, at least the above supermarket does not show up in the basemap (https://protomaps.github.io/PMTiles/?url=https%3A%2F%2Fr2-public.protomaps.com%2Fprotomaps-sample-datasets%2Fprotomaps-basemap-opensource-20230408.pmtiles#map=17.43/47.546268/7.952184)

@nvkelso do you plan to fix this in #47?

Thanks for all your work @bdon and @nvkelso. Will be an awesome basemap!

**Comment by nvkelso** [comment]
Yes, this is fixed in #47.

For https://www.openstreetmap.org/node/1730800437#map=16/47.5952/-122.3235 in Seattle, Washington:

<img width="1296" alt="image" src="https://github.com/protomaps/basemaps/assets/853051/d82b7e45-e857-457b-9bce-5445d37f14e2">

**Comment by nvkelso** [comment]
#47 has been merged, this issue can be closed as complete.
