### ISSUE TITLE
link roads missing from a generated map

### ISSUE THREAD

**Issue by andrey-abstracted** [protomaps/basemaps#53]
motorway_links and primary_links are present on OSM maps but missing when a freshly generated map is viewed using PMTiles viewer. 

In protomaps-basemap-opensource-20230408.pmtiles primary_links are present but motorway_links are not.

The screenshots are from the freshly generated map viewed using PMTiles viewer.

https://www.openstreetmap.org/way/454442266#map=18/-38.08778/145.32274
<img width="696" alt="Screenshot 2023-07-06 at 12 31 38 pm" src="https://github.com/protomaps/basemaps/assets/2003704/a5043cbc-4515-46c1-b3c0-aa84d0e5f693">
<img width="544" alt="Screenshot 2023-07-06 at 12 31 24 pm" src="https://github.com/protomaps/basemaps/assets/2003704/63688fbe-e9ff-472c-8b84-e4aa3e2367f5">

https://www.openstreetmap.org/way/454442266#map=15/-37.6831/144.9850
<img width="908" alt="Screenshot 2023-07-06 at 12 20 49 pm" src="https://github.com/protomaps/basemaps/assets/2003704/85a3aea7-a6b0-4af1-9b4b-8a7c35727628">
<img width="773" alt="Screenshot 2023-07-06 at 12 32 11 pm" src="https://github.com/protomaps/basemaps/assets/2003704/912e5a74-ff79-458d-8457-d1abab544308">

**Comment by bdon** [comment]
Thanks, I can verify that this is an issue in specific cases where links consist of multiple ways, working on a fix.

**Comment by bdon** [comment]
PR https://github.com/protomaps/basemaps/pull/57 is progress towards improving this, but the logic in LinkSimplify needs to change to handle more complex cases like the 2nd.

**Comment by pperzyna** [comment]
I generated new pmtiles for planet. Happy to share to update link on website. @bdon

**Comment by andrey-abstracted** [comment]
Great, thank you. On a slightly irrelevant note - would it be possible to change the zoom range for motorways from 12-15 to 11-15. That feature is quite a significant visual landmark and is still visible at lower zoom levels.

**Comment by bdon** [comment]
@andrey-abstracted a major rework of both the display style and base tileset is coming soon; The best option for right now though, and in the future, is to generate your own tileset while modifying the configuration to your needs. This will likely require a small modification to both Java code and JSON styles. 

Our goal is to make this kind of adjustment easy via configuration changes and/or style parameters, but that is a medium to long-term project.

**Comment by andrey-abstracted** [comment]
@bdon yes, absolutely, I've been doing that. In this particular case it felt like a better user experience but that is of course quite subjective.

**Comment by nvkelso** [comment]
I think this one can be closed as complete (link simplify bug).
