### ISSUE TITLE
adding natural:beach to the dataset

### ISSUE THREAD

**Issue by andrey-abstracted** [protomaps/basemaps#54]
Would it be possible to add natural:beach to the map?

**Comment by bdon** [comment]
yes, should be in scope for v4: `kind=beach` in the `landuse` layer [documented here](https://tilezen.readthedocs.io/en/latest/layers/)

**Comment by nvkelso** [comment]
Good news – adding `beach` features is already in my WIP PR https://github.com/protomaps/basemaps/pull/47, shown in the right hand side of the screenshot below:

<img width="1662" alt="image" src="https://github.com/protomaps/basemaps/assets/853051/2fc1c6f2-401d-492a-92f7-dda82dbb44f0">

**Comment by andrey-abstracted** [comment]
Great, thanks!

**Comment by nvkelso** [comment]
These has been merged to master, @bdon can you closing as complete?
