### ISSUE TITLE
Distinguishing railaway tunnels

### ISSUE THREAD

**Issue by andrey-abstracted** [protomaps/basemaps#55]
Would it possible to mark railaway tunnels as tunnels or underground structures? Possibly by setting pmap:level like it is done for road tunnels.

Currently in OSM they have "layer" set to -1 and "tunnel" to "yes".

**Comment by bdon** [comment]
Should come in the transportation later in v4:

https://tilezen.readthedocs.io/en/latest/layers/#roads-transportation

`is_bridge`, `is_tunnel` are the boolean tags.

**Comment by nvkelso** [comment]
This was completed for v3 via #47 and merged to main.
