### ISSUE TITLE
pedestrian features in tileset not visualized in style

### ISSUE THREAD

**Issue by andrey-abstracted** [protomaps/basemaps#67]
Sorry to bother again guys, this is just something that might benefit others.

The landuse_pedestrian needs the following added in the layout, currently it only checks for a "footway". 
Also needs to be moved below the "water" in the layout so that footbridges would stay afloat.

            [
                "==",
                "highway",
                "pedestrian"
            ],
            [
                "==",
               "pmap:kind",
               "pedestrian"
            ]

**Comment by bdon** [comment]
Thanks. there is currently a mismatch between the default style and tileset where not 100% of features are visualized. We are working on the project infrastructure to make change control more reliable in the future so there are lots of issues like this we will gradually get to. Please consolidate any other issues in this issue instead of opening a new one.

**Comment by bdon** [comment]
@andrey-abstracted for examples like this can you please also provide one of a screenshot, a zoom/lat/long, or both?

**Comment by andrey-abstracted** [comment]
@bdon apologies, this is certainly not how I intended to name this ticket. 

Everything related to "rail" needs the following added as currently we end up with railway drawn on top of transit_pier 

  "filter": [
      "any",
      [
          "==",
          "pmap:kind",
          "railway"
      ]
  ],

**Comment by andrey-abstracted** [comment]
The location for a footbridge is -33.87055828705787, 151.2008064875631.
There are some piers and foot walks around.
Additionally 
            "all",
            [
                "==",
                "pmap:level",
                0
            ],
            [
                "==",
                "pmap:kind",
                "other"
            ]
needs to be replace with pmap:kind = path as footwalks like on the screenshot do not appear on a recently created map

![Screenshot 2023-07-19 at 4 11 26 pm](https://github.com/protomaps/basemaps/assets/2003704/a08d400a-5052-448c-b75c-7558912883a6)

**Comment by bdon** [comment]
Fixed in style `2.0.0-alpha.4`: 

https://maps.protomaps.com/#map=17/-33.87182/151.20208&theme=light&renderer=maplibregl&tiles=https://build.protomaps.com/20231110.pmtiles&npm_version=2.0.0-alpha.4

**Comment by bdon** [comment]
> Everything related to "rail" needs the following added as currently we end up with railway drawn on top of transit_pier

I don't think this is true 100% of the case, it should depend on `layer` similar to highways? It would help to find a couple of examples.
