### ISSUE TITLE
Some state (region) lines aren't included from OSM

### ISSUE THREAD

**Issue by nvkelso** [protomaps/basemaps#88]
For example, Montana at zoom 6 from Natural Earth shows up fine. But zooming into 7 and OSM the feature isn't included in the `boundaries` layer in error.

- OSM relation for Montana: https://www.openstreetmap.org/relation/162115

Zoom 6: 

<img width="849" alt="image" src="https://github.com/protomaps/basemaps/assets/853051/9e020177-efd2-42f8-b44c-90d009c68abe">

Zoom 7: 

<img width="1237" alt="image" src="https://github.com/protomaps/basemaps/assets/853051/70e10a8a-82d2-498e-aabb-f46ef4862a2d">

**Comment by nvkelso** [comment]
I'll try building from Daylight instead

**Comment by bdon** [comment]
Should be resolved by #113, screenshot of Montana

<img width="863" alt="Screenshot 2023-08-31 at 09 46 41" src="https://github.com/protomaps/basemaps/assets/77501/a1e43d02-0fbc-4065-9e35-68a476eb5717">
